// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class CustomDomain extends pulumi.CustomResource {
    /**
     * Get an existing CustomDomain resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CustomDomainState, opts?: pulumi.CustomResourceOptions): CustomDomain {
        return new CustomDomain(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'railway:index/customDomain:CustomDomain';

    /**
     * Returns true if the given object is an instance of CustomDomain.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CustomDomain {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CustomDomain.__pulumiType;
    }

    /**
     * DNS record value of the custom domain.
     */
    declare public /*out*/ readonly dnsRecordValue: pulumi.Output<string>;
    /**
     * Custom domain.
     */
    declare public readonly domain: pulumi.Output<string>;
    /**
     * Identifier of the environment the custom domain belongs to.
     */
    declare public readonly environmentId: pulumi.Output<string>;
    /**
     * Host label of the custom domain.
     */
    declare public /*out*/ readonly hostLabel: pulumi.Output<string>;
    /**
     * Identifier of the project the custom domain belongs to.
     */
    declare public /*out*/ readonly projectId: pulumi.Output<string>;
    /**
     * Identifier of the service the custom domain belongs to.
     */
    declare public readonly serviceId: pulumi.Output<string>;
    /**
     * Target port of the service for the custom domain.
     */
    declare public readonly targetPort: pulumi.Output<number | undefined>;
    /**
     * DNS host label for custom domain verification
     */
    declare public /*out*/ readonly verificationHostLabel: pulumi.Output<string>;
    /**
     * DNS record value for custom domain verification
     */
    declare public /*out*/ readonly verificationRecordValue: pulumi.Output<string>;
    /**
     * Zone of the custom domain.
     */
    declare public /*out*/ readonly zone: pulumi.Output<string>;

    /**
     * Create a CustomDomain resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CustomDomainArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CustomDomainArgs | CustomDomainState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CustomDomainState | undefined;
            resourceInputs["dnsRecordValue"] = state?.dnsRecordValue;
            resourceInputs["domain"] = state?.domain;
            resourceInputs["environmentId"] = state?.environmentId;
            resourceInputs["hostLabel"] = state?.hostLabel;
            resourceInputs["projectId"] = state?.projectId;
            resourceInputs["serviceId"] = state?.serviceId;
            resourceInputs["targetPort"] = state?.targetPort;
            resourceInputs["verificationHostLabel"] = state?.verificationHostLabel;
            resourceInputs["verificationRecordValue"] = state?.verificationRecordValue;
            resourceInputs["zone"] = state?.zone;
        } else {
            const args = argsOrState as CustomDomainArgs | undefined;
            if (args?.domain === undefined && !opts.urn) {
                throw new Error("Missing required property 'domain'");
            }
            if (args?.environmentId === undefined && !opts.urn) {
                throw new Error("Missing required property 'environmentId'");
            }
            if (args?.serviceId === undefined && !opts.urn) {
                throw new Error("Missing required property 'serviceId'");
            }
            resourceInputs["domain"] = args?.domain;
            resourceInputs["environmentId"] = args?.environmentId;
            resourceInputs["serviceId"] = args?.serviceId;
            resourceInputs["targetPort"] = args?.targetPort;
            resourceInputs["dnsRecordValue"] = undefined /*out*/;
            resourceInputs["hostLabel"] = undefined /*out*/;
            resourceInputs["projectId"] = undefined /*out*/;
            resourceInputs["verificationHostLabel"] = undefined /*out*/;
            resourceInputs["verificationRecordValue"] = undefined /*out*/;
            resourceInputs["zone"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CustomDomain.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering CustomDomain resources.
 */
export interface CustomDomainState {
    /**
     * DNS record value of the custom domain.
     */
    dnsRecordValue?: pulumi.Input<string | undefined>;
    /**
     * Custom domain.
     */
    domain?: pulumi.Input<string | undefined>;
    /**
     * Identifier of the environment the custom domain belongs to.
     */
    environmentId?: pulumi.Input<string | undefined>;
    /**
     * Host label of the custom domain.
     */
    hostLabel?: pulumi.Input<string | undefined>;
    /**
     * Identifier of the project the custom domain belongs to.
     */
    projectId?: pulumi.Input<string | undefined>;
    /**
     * Identifier of the service the custom domain belongs to.
     */
    serviceId?: pulumi.Input<string | undefined>;
    /**
     * Target port of the service for the custom domain.
     */
    targetPort?: pulumi.Input<number | undefined>;
    /**
     * DNS host label for custom domain verification
     */
    verificationHostLabel?: pulumi.Input<string | undefined>;
    /**
     * DNS record value for custom domain verification
     */
    verificationRecordValue?: pulumi.Input<string | undefined>;
    /**
     * Zone of the custom domain.
     */
    zone?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a CustomDomain resource.
 */
export interface CustomDomainArgs {
    /**
     * Custom domain.
     */
    domain: pulumi.Input<string>;
    /**
     * Identifier of the environment the custom domain belongs to.
     */
    environmentId: pulumi.Input<string>;
    /**
     * Identifier of the service the custom domain belongs to.
     */
    serviceId: pulumi.Input<string>;
    /**
     * Target port of the service for the custom domain.
     */
    targetPort?: pulumi.Input<number | undefined>;
}
