// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { CustomDomainArgs, CustomDomainState } from "./customDomain";
export type CustomDomain = import("./customDomain").CustomDomain;
export const CustomDomain: typeof import("./customDomain").CustomDomain = null as any;
utilities.lazyLoad(exports, ["CustomDomain"], () => require("./customDomain"));

export { EnvironmentArgs, EnvironmentState } from "./environment";
export type Environment = import("./environment").Environment;
export const Environment: typeof import("./environment").Environment = null as any;
utilities.lazyLoad(exports, ["Environment"], () => require("./environment"));

export { ProjectArgs, ProjectState } from "./project";
export type Project = import("./project").Project;
export const Project: typeof import("./project").Project = null as any;
utilities.lazyLoad(exports, ["Project"], () => require("./project"));

export * from "./provider";
import { Provider } from "./provider";

export { ServiceArgs, ServiceState } from "./service";
export type Service = import("./service").Service;
export const Service: typeof import("./service").Service = null as any;
utilities.lazyLoad(exports, ["Service"], () => require("./service"));

export { ServiceDomainArgs, ServiceDomainState } from "./serviceDomain";
export type ServiceDomain = import("./serviceDomain").ServiceDomain;
export const ServiceDomain: typeof import("./serviceDomain").ServiceDomain = null as any;
utilities.lazyLoad(exports, ["ServiceDomain"], () => require("./serviceDomain"));

export { SharedVariableArgs, SharedVariableState } from "./sharedVariable";
export type SharedVariable = import("./sharedVariable").SharedVariable;
export const SharedVariable: typeof import("./sharedVariable").SharedVariable = null as any;
utilities.lazyLoad(exports, ["SharedVariable"], () => require("./sharedVariable"));

export { TcpProxyArgs, TcpProxyState } from "./tcpProxy";
export type TcpProxy = import("./tcpProxy").TcpProxy;
export const TcpProxy: typeof import("./tcpProxy").TcpProxy = null as any;
utilities.lazyLoad(exports, ["TcpProxy"], () => require("./tcpProxy"));

export { VariableArgs, VariableState } from "./variable";
export type Variable = import("./variable").Variable;
export const Variable: typeof import("./variable").Variable = null as any;
utilities.lazyLoad(exports, ["Variable"], () => require("./variable"));

export { VariableCollectionArgs, VariableCollectionState } from "./variableCollection";
export type VariableCollection = import("./variableCollection").VariableCollection;
export const VariableCollection: typeof import("./variableCollection").VariableCollection = null as any;
utilities.lazyLoad(exports, ["VariableCollection"], () => require("./variableCollection"));


// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "railway:index/customDomain:CustomDomain":
                return new CustomDomain(name, <any>undefined, { urn })
            case "railway:index/environment:Environment":
                return new Environment(name, <any>undefined, { urn })
            case "railway:index/project:Project":
                return new Project(name, <any>undefined, { urn })
            case "railway:index/service:Service":
                return new Service(name, <any>undefined, { urn })
            case "railway:index/serviceDomain:ServiceDomain":
                return new ServiceDomain(name, <any>undefined, { urn })
            case "railway:index/sharedVariable:SharedVariable":
                return new SharedVariable(name, <any>undefined, { urn })
            case "railway:index/tcpProxy:TcpProxy":
                return new TcpProxy(name, <any>undefined, { urn })
            case "railway:index/variable:Variable":
                return new Variable(name, <any>undefined, { urn })
            case "railway:index/variableCollection:VariableCollection":
                return new VariableCollection(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("railway", "index/customDomain", _module)
pulumi.runtime.registerResourceModule("railway", "index/environment", _module)
pulumi.runtime.registerResourceModule("railway", "index/project", _module)
pulumi.runtime.registerResourceModule("railway", "index/service", _module)
pulumi.runtime.registerResourceModule("railway", "index/serviceDomain", _module)
pulumi.runtime.registerResourceModule("railway", "index/sharedVariable", _module)
pulumi.runtime.registerResourceModule("railway", "index/tcpProxy", _module)
pulumi.runtime.registerResourceModule("railway", "index/variable", _module)
pulumi.runtime.registerResourceModule("railway", "index/variableCollection", _module)
pulumi.runtime.registerResourcePackage("railway", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:railway") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
