// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Project extends pulumi.CustomResource {
    /**
     * Get an existing Project resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ProjectState, opts?: pulumi.CustomResourceOptions): Project {
        return new Project(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'railway:index/project:Project';

    /**
     * Returns true if the given object is an instance of Project.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Project {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Project.__pulumiType;
    }

    /**
     * Default environment of the project. When multiple exist, the oldest is considered.
     */
    declare public readonly defaultEnvironment: pulumi.Output<outputs.ProjectDefaultEnvironment>;
    /**
     * Description of the project.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * Whether the project has PR deploys enabled. **Default** <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
     */
    declare public readonly hasPrDeploys: pulumi.Output<boolean>;
    /**
     * Name of the project.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Privacy of the project. **Default** <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    declare public readonly private: pulumi.Output<boolean>;
    /**
     * Identifier of the workspace the project belongs to. Required if the railway token has access to multiple workspaces.
     */
    declare public readonly workspaceId: pulumi.Output<string>;

    /**
     * Create a Project resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ProjectArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ProjectArgs | ProjectState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ProjectState | undefined;
            resourceInputs["defaultEnvironment"] = state?.defaultEnvironment;
            resourceInputs["description"] = state?.description;
            resourceInputs["hasPrDeploys"] = state?.hasPrDeploys;
            resourceInputs["name"] = state?.name;
            resourceInputs["private"] = state?.private;
            resourceInputs["workspaceId"] = state?.workspaceId;
        } else {
            const args = argsOrState as ProjectArgs | undefined;
            resourceInputs["defaultEnvironment"] = args?.defaultEnvironment;
            resourceInputs["description"] = args?.description;
            resourceInputs["hasPrDeploys"] = args?.hasPrDeploys;
            resourceInputs["name"] = args?.name;
            resourceInputs["private"] = args?.private;
            resourceInputs["workspaceId"] = args?.workspaceId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Project.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Project resources.
 */
export interface ProjectState {
    /**
     * Default environment of the project. When multiple exist, the oldest is considered.
     */
    defaultEnvironment?: pulumi.Input<inputs.ProjectDefaultEnvironment | undefined>;
    /**
     * Description of the project.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Whether the project has PR deploys enabled. **Default** <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
     */
    hasPrDeploys?: pulumi.Input<boolean | undefined>;
    /**
     * Name of the project.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Privacy of the project. **Default** <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    private?: pulumi.Input<boolean | undefined>;
    /**
     * Identifier of the workspace the project belongs to. Required if the railway token has access to multiple workspaces.
     */
    workspaceId?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Project resource.
 */
export interface ProjectArgs {
    /**
     * Default environment of the project. When multiple exist, the oldest is considered.
     */
    defaultEnvironment?: pulumi.Input<inputs.ProjectDefaultEnvironment | undefined>;
    /**
     * Description of the project.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Whether the project has PR deploys enabled. **Default** <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
     */
    hasPrDeploys?: pulumi.Input<boolean | undefined>;
    /**
     * Name of the project.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Privacy of the project. **Default** <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    private?: pulumi.Input<boolean | undefined>;
    /**
     * Identifier of the workspace the project belongs to. Required if the railway token has access to multiple workspaces.
     */
    workspaceId?: pulumi.Input<string | undefined>;
}
