// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Service extends pulumi.CustomResource {
    /**
     * Get an existing Service resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ServiceState, opts?: pulumi.CustomResourceOptions): Service {
        return new Service(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'railway:index/service:Service';

    /**
     * Returns true if the given object is an instance of Service.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Service {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Service.__pulumiType;
    }

    /**
     * Path to the Railway config file. Conflicts with <span pulumi-lang-nodejs="`sourceImage`" pulumi-lang-dotnet="`SourceImage`" pulumi-lang-go="`sourceImage`" pulumi-lang-python="`source_image`" pulumi-lang-yaml="`sourceImage`" pulumi-lang-java="`sourceImage`" pulumi-lang-hcl="`source_image`">`sourceImage`</span>.
     */
    declare public readonly configPath: pulumi.Output<string | undefined>;
    /**
     * Cron schedule of the service. Only allowed when total number of replicas across all regions is <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span>.
     */
    declare public readonly cronSchedule: pulumi.Output<string | undefined>;
    /**
     * Name of the service.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Identifier of the project the service belongs to.
     */
    declare public readonly projectId: pulumi.Output<string>;
    /**
     * Regions with replicas to deploy service in.
     */
    declare public readonly regions: pulumi.Output<outputs.ServiceRegion[]>;
    /**
     * Directory to user for the service. Conflicts with <span pulumi-lang-nodejs="`sourceImage`" pulumi-lang-dotnet="`SourceImage`" pulumi-lang-go="`sourceImage`" pulumi-lang-python="`source_image`" pulumi-lang-yaml="`sourceImage`" pulumi-lang-java="`sourceImage`" pulumi-lang-hcl="`source_image`">`sourceImage`</span>.
     */
    declare public readonly rootDirectory: pulumi.Output<string | undefined>;
    /**
     * Source image of the service. Conflicts with <span pulumi-lang-nodejs="`sourceRepo`" pulumi-lang-dotnet="`SourceRepo`" pulumi-lang-go="`sourceRepo`" pulumi-lang-python="`source_repo`" pulumi-lang-yaml="`sourceRepo`" pulumi-lang-java="`sourceRepo`" pulumi-lang-hcl="`source_repo`">`sourceRepo`</span>, <span pulumi-lang-nodejs="`sourceRepoBranch`" pulumi-lang-dotnet="`SourceRepoBranch`" pulumi-lang-go="`sourceRepoBranch`" pulumi-lang-python="`source_repo_branch`" pulumi-lang-yaml="`sourceRepoBranch`" pulumi-lang-java="`sourceRepoBranch`" pulumi-lang-hcl="`source_repo_branch`">`sourceRepoBranch`</span>, <span pulumi-lang-nodejs="`rootDirectory`" pulumi-lang-dotnet="`RootDirectory`" pulumi-lang-go="`rootDirectory`" pulumi-lang-python="`root_directory`" pulumi-lang-yaml="`rootDirectory`" pulumi-lang-java="`rootDirectory`" pulumi-lang-hcl="`root_directory`">`rootDirectory`</span> and <span pulumi-lang-nodejs="`configPath`" pulumi-lang-dotnet="`ConfigPath`" pulumi-lang-go="`configPath`" pulumi-lang-python="`config_path`" pulumi-lang-yaml="`configPath`" pulumi-lang-java="`configPath`" pulumi-lang-hcl="`config_path`">`configPath`</span>.
     */
    declare public readonly sourceImage: pulumi.Output<string | undefined>;
    /**
     * Private Docker registry credentials.
     */
    declare public readonly sourceImageRegistryPassword: pulumi.Output<string | undefined>;
    /**
     * Private Docker registry credentials.
     */
    declare public readonly sourceImageRegistryUsername: pulumi.Output<string | undefined>;
    /**
     * Source repository of the service. Conflicts with <span pulumi-lang-nodejs="`sourceImage`" pulumi-lang-dotnet="`SourceImage`" pulumi-lang-go="`sourceImage`" pulumi-lang-python="`source_image`" pulumi-lang-yaml="`sourceImage`" pulumi-lang-java="`sourceImage`" pulumi-lang-hcl="`source_image`">`sourceImage`</span>.
     */
    declare public readonly sourceRepo: pulumi.Output<string | undefined>;
    /**
     * Source repository branch to be used with <span pulumi-lang-nodejs="`sourceRepo`" pulumi-lang-dotnet="`SourceRepo`" pulumi-lang-go="`sourceRepo`" pulumi-lang-python="`source_repo`" pulumi-lang-yaml="`sourceRepo`" pulumi-lang-java="`sourceRepo`" pulumi-lang-hcl="`source_repo`">`sourceRepo`</span>. Must be specified if <span pulumi-lang-nodejs="`sourceRepo`" pulumi-lang-dotnet="`SourceRepo`" pulumi-lang-go="`sourceRepo`" pulumi-lang-python="`source_repo`" pulumi-lang-yaml="`sourceRepo`" pulumi-lang-java="`sourceRepo`" pulumi-lang-hcl="`source_repo`">`sourceRepo`</span> is specified.
     */
    declare public readonly sourceRepoBranch: pulumi.Output<string | undefined>;
    /**
     * Volume connected to the service.
     */
    declare public readonly volume: pulumi.Output<outputs.ServiceVolume | undefined>;

    /**
     * Create a Service resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ServiceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ServiceArgs | ServiceState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ServiceState | undefined;
            resourceInputs["configPath"] = state?.configPath;
            resourceInputs["cronSchedule"] = state?.cronSchedule;
            resourceInputs["name"] = state?.name;
            resourceInputs["projectId"] = state?.projectId;
            resourceInputs["regions"] = state?.regions;
            resourceInputs["rootDirectory"] = state?.rootDirectory;
            resourceInputs["sourceImage"] = state?.sourceImage;
            resourceInputs["sourceImageRegistryPassword"] = state?.sourceImageRegistryPassword;
            resourceInputs["sourceImageRegistryUsername"] = state?.sourceImageRegistryUsername;
            resourceInputs["sourceRepo"] = state?.sourceRepo;
            resourceInputs["sourceRepoBranch"] = state?.sourceRepoBranch;
            resourceInputs["volume"] = state?.volume;
        } else {
            const args = argsOrState as ServiceArgs | undefined;
            if (args?.projectId === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectId'");
            }
            resourceInputs["configPath"] = args?.configPath;
            resourceInputs["cronSchedule"] = args?.cronSchedule;
            resourceInputs["name"] = args?.name;
            resourceInputs["projectId"] = args?.projectId;
            resourceInputs["regions"] = args?.regions;
            resourceInputs["rootDirectory"] = args?.rootDirectory;
            resourceInputs["sourceImage"] = args?.sourceImage;
            resourceInputs["sourceImageRegistryPassword"] = args?.sourceImageRegistryPassword ? pulumi.secret(args.sourceImageRegistryPassword) : undefined;
            resourceInputs["sourceImageRegistryUsername"] = args?.sourceImageRegistryUsername;
            resourceInputs["sourceRepo"] = args?.sourceRepo;
            resourceInputs["sourceRepoBranch"] = args?.sourceRepoBranch;
            resourceInputs["volume"] = args?.volume;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["sourceImageRegistryPassword"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Service.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Service resources.
 */
export interface ServiceState {
    /**
     * Path to the Railway config file. Conflicts with <span pulumi-lang-nodejs="`sourceImage`" pulumi-lang-dotnet="`SourceImage`" pulumi-lang-go="`sourceImage`" pulumi-lang-python="`source_image`" pulumi-lang-yaml="`sourceImage`" pulumi-lang-java="`sourceImage`" pulumi-lang-hcl="`source_image`">`sourceImage`</span>.
     */
    configPath?: pulumi.Input<string | undefined>;
    /**
     * Cron schedule of the service. Only allowed when total number of replicas across all regions is <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span>.
     */
    cronSchedule?: pulumi.Input<string | undefined>;
    /**
     * Name of the service.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Identifier of the project the service belongs to.
     */
    projectId?: pulumi.Input<string | undefined>;
    /**
     * Regions with replicas to deploy service in.
     */
    regions?: pulumi.Input<pulumi.Input<inputs.ServiceRegion>[] | undefined>;
    /**
     * Directory to user for the service. Conflicts with <span pulumi-lang-nodejs="`sourceImage`" pulumi-lang-dotnet="`SourceImage`" pulumi-lang-go="`sourceImage`" pulumi-lang-python="`source_image`" pulumi-lang-yaml="`sourceImage`" pulumi-lang-java="`sourceImage`" pulumi-lang-hcl="`source_image`">`sourceImage`</span>.
     */
    rootDirectory?: pulumi.Input<string | undefined>;
    /**
     * Source image of the service. Conflicts with <span pulumi-lang-nodejs="`sourceRepo`" pulumi-lang-dotnet="`SourceRepo`" pulumi-lang-go="`sourceRepo`" pulumi-lang-python="`source_repo`" pulumi-lang-yaml="`sourceRepo`" pulumi-lang-java="`sourceRepo`" pulumi-lang-hcl="`source_repo`">`sourceRepo`</span>, <span pulumi-lang-nodejs="`sourceRepoBranch`" pulumi-lang-dotnet="`SourceRepoBranch`" pulumi-lang-go="`sourceRepoBranch`" pulumi-lang-python="`source_repo_branch`" pulumi-lang-yaml="`sourceRepoBranch`" pulumi-lang-java="`sourceRepoBranch`" pulumi-lang-hcl="`source_repo_branch`">`sourceRepoBranch`</span>, <span pulumi-lang-nodejs="`rootDirectory`" pulumi-lang-dotnet="`RootDirectory`" pulumi-lang-go="`rootDirectory`" pulumi-lang-python="`root_directory`" pulumi-lang-yaml="`rootDirectory`" pulumi-lang-java="`rootDirectory`" pulumi-lang-hcl="`root_directory`">`rootDirectory`</span> and <span pulumi-lang-nodejs="`configPath`" pulumi-lang-dotnet="`ConfigPath`" pulumi-lang-go="`configPath`" pulumi-lang-python="`config_path`" pulumi-lang-yaml="`configPath`" pulumi-lang-java="`configPath`" pulumi-lang-hcl="`config_path`">`configPath`</span>.
     */
    sourceImage?: pulumi.Input<string | undefined>;
    /**
     * Private Docker registry credentials.
     */
    sourceImageRegistryPassword?: pulumi.Input<string | undefined>;
    /**
     * Private Docker registry credentials.
     */
    sourceImageRegistryUsername?: pulumi.Input<string | undefined>;
    /**
     * Source repository of the service. Conflicts with <span pulumi-lang-nodejs="`sourceImage`" pulumi-lang-dotnet="`SourceImage`" pulumi-lang-go="`sourceImage`" pulumi-lang-python="`source_image`" pulumi-lang-yaml="`sourceImage`" pulumi-lang-java="`sourceImage`" pulumi-lang-hcl="`source_image`">`sourceImage`</span>.
     */
    sourceRepo?: pulumi.Input<string | undefined>;
    /**
     * Source repository branch to be used with <span pulumi-lang-nodejs="`sourceRepo`" pulumi-lang-dotnet="`SourceRepo`" pulumi-lang-go="`sourceRepo`" pulumi-lang-python="`source_repo`" pulumi-lang-yaml="`sourceRepo`" pulumi-lang-java="`sourceRepo`" pulumi-lang-hcl="`source_repo`">`sourceRepo`</span>. Must be specified if <span pulumi-lang-nodejs="`sourceRepo`" pulumi-lang-dotnet="`SourceRepo`" pulumi-lang-go="`sourceRepo`" pulumi-lang-python="`source_repo`" pulumi-lang-yaml="`sourceRepo`" pulumi-lang-java="`sourceRepo`" pulumi-lang-hcl="`source_repo`">`sourceRepo`</span> is specified.
     */
    sourceRepoBranch?: pulumi.Input<string | undefined>;
    /**
     * Volume connected to the service.
     */
    volume?: pulumi.Input<inputs.ServiceVolume | undefined>;
}

/**
 * The set of arguments for constructing a Service resource.
 */
export interface ServiceArgs {
    /**
     * Path to the Railway config file. Conflicts with <span pulumi-lang-nodejs="`sourceImage`" pulumi-lang-dotnet="`SourceImage`" pulumi-lang-go="`sourceImage`" pulumi-lang-python="`source_image`" pulumi-lang-yaml="`sourceImage`" pulumi-lang-java="`sourceImage`" pulumi-lang-hcl="`source_image`">`sourceImage`</span>.
     */
    configPath?: pulumi.Input<string | undefined>;
    /**
     * Cron schedule of the service. Only allowed when total number of replicas across all regions is <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span>.
     */
    cronSchedule?: pulumi.Input<string | undefined>;
    /**
     * Name of the service.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Identifier of the project the service belongs to.
     */
    projectId: pulumi.Input<string>;
    /**
     * Regions with replicas to deploy service in.
     */
    regions?: pulumi.Input<pulumi.Input<inputs.ServiceRegion>[] | undefined>;
    /**
     * Directory to user for the service. Conflicts with <span pulumi-lang-nodejs="`sourceImage`" pulumi-lang-dotnet="`SourceImage`" pulumi-lang-go="`sourceImage`" pulumi-lang-python="`source_image`" pulumi-lang-yaml="`sourceImage`" pulumi-lang-java="`sourceImage`" pulumi-lang-hcl="`source_image`">`sourceImage`</span>.
     */
    rootDirectory?: pulumi.Input<string | undefined>;
    /**
     * Source image of the service. Conflicts with <span pulumi-lang-nodejs="`sourceRepo`" pulumi-lang-dotnet="`SourceRepo`" pulumi-lang-go="`sourceRepo`" pulumi-lang-python="`source_repo`" pulumi-lang-yaml="`sourceRepo`" pulumi-lang-java="`sourceRepo`" pulumi-lang-hcl="`source_repo`">`sourceRepo`</span>, <span pulumi-lang-nodejs="`sourceRepoBranch`" pulumi-lang-dotnet="`SourceRepoBranch`" pulumi-lang-go="`sourceRepoBranch`" pulumi-lang-python="`source_repo_branch`" pulumi-lang-yaml="`sourceRepoBranch`" pulumi-lang-java="`sourceRepoBranch`" pulumi-lang-hcl="`source_repo_branch`">`sourceRepoBranch`</span>, <span pulumi-lang-nodejs="`rootDirectory`" pulumi-lang-dotnet="`RootDirectory`" pulumi-lang-go="`rootDirectory`" pulumi-lang-python="`root_directory`" pulumi-lang-yaml="`rootDirectory`" pulumi-lang-java="`rootDirectory`" pulumi-lang-hcl="`root_directory`">`rootDirectory`</span> and <span pulumi-lang-nodejs="`configPath`" pulumi-lang-dotnet="`ConfigPath`" pulumi-lang-go="`configPath`" pulumi-lang-python="`config_path`" pulumi-lang-yaml="`configPath`" pulumi-lang-java="`configPath`" pulumi-lang-hcl="`config_path`">`configPath`</span>.
     */
    sourceImage?: pulumi.Input<string | undefined>;
    /**
     * Private Docker registry credentials.
     */
    sourceImageRegistryPassword?: pulumi.Input<string | undefined>;
    /**
     * Private Docker registry credentials.
     */
    sourceImageRegistryUsername?: pulumi.Input<string | undefined>;
    /**
     * Source repository of the service. Conflicts with <span pulumi-lang-nodejs="`sourceImage`" pulumi-lang-dotnet="`SourceImage`" pulumi-lang-go="`sourceImage`" pulumi-lang-python="`source_image`" pulumi-lang-yaml="`sourceImage`" pulumi-lang-java="`sourceImage`" pulumi-lang-hcl="`source_image`">`sourceImage`</span>.
     */
    sourceRepo?: pulumi.Input<string | undefined>;
    /**
     * Source repository branch to be used with <span pulumi-lang-nodejs="`sourceRepo`" pulumi-lang-dotnet="`SourceRepo`" pulumi-lang-go="`sourceRepo`" pulumi-lang-python="`source_repo`" pulumi-lang-yaml="`sourceRepo`" pulumi-lang-java="`sourceRepo`" pulumi-lang-hcl="`source_repo`">`sourceRepo`</span>. Must be specified if <span pulumi-lang-nodejs="`sourceRepo`" pulumi-lang-dotnet="`SourceRepo`" pulumi-lang-go="`sourceRepo`" pulumi-lang-python="`source_repo`" pulumi-lang-yaml="`sourceRepo`" pulumi-lang-java="`sourceRepo`" pulumi-lang-hcl="`source_repo`">`sourceRepo`</span> is specified.
     */
    sourceRepoBranch?: pulumi.Input<string | undefined>;
    /**
     * Volume connected to the service.
     */
    volume?: pulumi.Input<inputs.ServiceVolume | undefined>;
}
