// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ServiceDomain extends pulumi.CustomResource {
    /**
     * Get an existing ServiceDomain resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ServiceDomainState, opts?: pulumi.CustomResourceOptions): ServiceDomain {
        return new ServiceDomain(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'railway:index/serviceDomain:ServiceDomain';

    /**
     * Returns true if the given object is an instance of ServiceDomain.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ServiceDomain {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ServiceDomain.__pulumiType;
    }

    /**
     * Full domain of the service domain.
     */
    declare public /*out*/ readonly domain: pulumi.Output<string>;
    /**
     * Identifier of the environment the service domain belongs to.
     */
    declare public readonly environmentId: pulumi.Output<string>;
    /**
     * Identifier of the project the service domain belongs to.
     */
    declare public /*out*/ readonly projectId: pulumi.Output<string>;
    /**
     * Identifier of the service the service domain belongs to.
     */
    declare public readonly serviceId: pulumi.Output<string>;
    /**
     * Subdomain of the service domain.
     */
    declare public readonly subdomain: pulumi.Output<string>;
    /**
     * Suffix of the service domain.
     */
    declare public /*out*/ readonly suffix: pulumi.Output<string>;

    /**
     * Create a ServiceDomain resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ServiceDomainArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ServiceDomainArgs | ServiceDomainState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ServiceDomainState | undefined;
            resourceInputs["domain"] = state?.domain;
            resourceInputs["environmentId"] = state?.environmentId;
            resourceInputs["projectId"] = state?.projectId;
            resourceInputs["serviceId"] = state?.serviceId;
            resourceInputs["subdomain"] = state?.subdomain;
            resourceInputs["suffix"] = state?.suffix;
        } else {
            const args = argsOrState as ServiceDomainArgs | undefined;
            if (args?.environmentId === undefined && !opts.urn) {
                throw new Error("Missing required property 'environmentId'");
            }
            if (args?.serviceId === undefined && !opts.urn) {
                throw new Error("Missing required property 'serviceId'");
            }
            if (args?.subdomain === undefined && !opts.urn) {
                throw new Error("Missing required property 'subdomain'");
            }
            resourceInputs["environmentId"] = args?.environmentId;
            resourceInputs["serviceId"] = args?.serviceId;
            resourceInputs["subdomain"] = args?.subdomain;
            resourceInputs["domain"] = undefined /*out*/;
            resourceInputs["projectId"] = undefined /*out*/;
            resourceInputs["suffix"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ServiceDomain.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering ServiceDomain resources.
 */
export interface ServiceDomainState {
    /**
     * Full domain of the service domain.
     */
    domain?: pulumi.Input<string | undefined>;
    /**
     * Identifier of the environment the service domain belongs to.
     */
    environmentId?: pulumi.Input<string | undefined>;
    /**
     * Identifier of the project the service domain belongs to.
     */
    projectId?: pulumi.Input<string | undefined>;
    /**
     * Identifier of the service the service domain belongs to.
     */
    serviceId?: pulumi.Input<string | undefined>;
    /**
     * Subdomain of the service domain.
     */
    subdomain?: pulumi.Input<string | undefined>;
    /**
     * Suffix of the service domain.
     */
    suffix?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ServiceDomain resource.
 */
export interface ServiceDomainArgs {
    /**
     * Identifier of the environment the service domain belongs to.
     */
    environmentId: pulumi.Input<string>;
    /**
     * Identifier of the service the service domain belongs to.
     */
    serviceId: pulumi.Input<string>;
    /**
     * Subdomain of the service domain.
     */
    subdomain: pulumi.Input<string>;
}
