// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class SharedVariable extends pulumi.CustomResource {
    /**
     * Get an existing SharedVariable resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SharedVariableState, opts?: pulumi.CustomResourceOptions): SharedVariable {
        return new SharedVariable(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'railway:index/sharedVariable:SharedVariable';

    /**
     * Returns true if the given object is an instance of SharedVariable.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SharedVariable {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SharedVariable.__pulumiType;
    }

    /**
     * Identifier of the environment the variable belongs to.
     */
    declare public readonly environmentId: pulumi.Output<string>;
    /**
     * Name of the variable.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Identifier of the project the variable belongs to.
     */
    declare public readonly projectId: pulumi.Output<string>;
    /**
     * Value of the variable.
     */
    declare public readonly value: pulumi.Output<string>;

    /**
     * Create a SharedVariable resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SharedVariableArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SharedVariableArgs | SharedVariableState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SharedVariableState | undefined;
            resourceInputs["environmentId"] = state?.environmentId;
            resourceInputs["name"] = state?.name;
            resourceInputs["projectId"] = state?.projectId;
            resourceInputs["value"] = state?.value;
        } else {
            const args = argsOrState as SharedVariableArgs | undefined;
            if (args?.environmentId === undefined && !opts.urn) {
                throw new Error("Missing required property 'environmentId'");
            }
            if (args?.projectId === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectId'");
            }
            if (args?.value === undefined && !opts.urn) {
                throw new Error("Missing required property 'value'");
            }
            resourceInputs["environmentId"] = args?.environmentId;
            resourceInputs["name"] = args?.name;
            resourceInputs["projectId"] = args?.projectId;
            resourceInputs["value"] = args?.value ? pulumi.secret(args.value) : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["value"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(SharedVariable.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering SharedVariable resources.
 */
export interface SharedVariableState {
    /**
     * Identifier of the environment the variable belongs to.
     */
    environmentId?: pulumi.Input<string | undefined>;
    /**
     * Name of the variable.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Identifier of the project the variable belongs to.
     */
    projectId?: pulumi.Input<string | undefined>;
    /**
     * Value of the variable.
     */
    value?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a SharedVariable resource.
 */
export interface SharedVariableArgs {
    /**
     * Identifier of the environment the variable belongs to.
     */
    environmentId: pulumi.Input<string>;
    /**
     * Name of the variable.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Identifier of the project the variable belongs to.
     */
    projectId: pulumi.Input<string>;
    /**
     * Value of the variable.
     */
    value: pulumi.Input<string>;
}
