// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class TcpProxy extends pulumi.CustomResource {
    /**
     * Get an existing TcpProxy resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TcpProxyState, opts?: pulumi.CustomResourceOptions): TcpProxy {
        return new TcpProxy(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'railway:index/tcpProxy:TcpProxy';

    /**
     * Returns true if the given object is an instance of TcpProxy.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is TcpProxy {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === TcpProxy.__pulumiType;
    }

    /**
     * Port of the application the TCP proxy points to.
     */
    declare public readonly applicationPort: pulumi.Output<number>;
    /**
     * Domain of the TCP proxy.
     */
    declare public /*out*/ readonly domain: pulumi.Output<string>;
    /**
     * Identifier of the environment the TCP proxy belongs to.
     */
    declare public readonly environmentId: pulumi.Output<string>;
    /**
     * Port of the TCP proxy.
     */
    declare public /*out*/ readonly proxyPort: pulumi.Output<number>;
    /**
     * Identifier of the service the TCP proxy belongs to.
     */
    declare public readonly serviceId: pulumi.Output<string>;

    /**
     * Create a TcpProxy resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TcpProxyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TcpProxyArgs | TcpProxyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TcpProxyState | undefined;
            resourceInputs["applicationPort"] = state?.applicationPort;
            resourceInputs["domain"] = state?.domain;
            resourceInputs["environmentId"] = state?.environmentId;
            resourceInputs["proxyPort"] = state?.proxyPort;
            resourceInputs["serviceId"] = state?.serviceId;
        } else {
            const args = argsOrState as TcpProxyArgs | undefined;
            if (args?.applicationPort === undefined && !opts.urn) {
                throw new Error("Missing required property 'applicationPort'");
            }
            if (args?.environmentId === undefined && !opts.urn) {
                throw new Error("Missing required property 'environmentId'");
            }
            if (args?.serviceId === undefined && !opts.urn) {
                throw new Error("Missing required property 'serviceId'");
            }
            resourceInputs["applicationPort"] = args?.applicationPort;
            resourceInputs["environmentId"] = args?.environmentId;
            resourceInputs["serviceId"] = args?.serviceId;
            resourceInputs["domain"] = undefined /*out*/;
            resourceInputs["proxyPort"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(TcpProxy.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering TcpProxy resources.
 */
export interface TcpProxyState {
    /**
     * Port of the application the TCP proxy points to.
     */
    applicationPort?: pulumi.Input<number | undefined>;
    /**
     * Domain of the TCP proxy.
     */
    domain?: pulumi.Input<string | undefined>;
    /**
     * Identifier of the environment the TCP proxy belongs to.
     */
    environmentId?: pulumi.Input<string | undefined>;
    /**
     * Port of the TCP proxy.
     */
    proxyPort?: pulumi.Input<number | undefined>;
    /**
     * Identifier of the service the TCP proxy belongs to.
     */
    serviceId?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a TcpProxy resource.
 */
export interface TcpProxyArgs {
    /**
     * Port of the application the TCP proxy points to.
     */
    applicationPort: pulumi.Input<number>;
    /**
     * Identifier of the environment the TCP proxy belongs to.
     */
    environmentId: pulumi.Input<string>;
    /**
     * Identifier of the service the TCP proxy belongs to.
     */
    serviceId: pulumi.Input<string>;
}
