// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class VariableCollection extends pulumi.CustomResource {
    /**
     * Get an existing VariableCollection resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: VariableCollectionState, opts?: pulumi.CustomResourceOptions): VariableCollection {
        return new VariableCollection(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'railway:index/variableCollection:VariableCollection';

    /**
     * Returns true if the given object is an instance of VariableCollection.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is VariableCollection {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === VariableCollection.__pulumiType;
    }

    /**
     * Identifier of the environment the variable collection belongs to.
     */
    declare public readonly environmentId: pulumi.Output<string>;
    /**
     * Identifier of the project the variable collection belongs to.
     */
    declare public /*out*/ readonly projectId: pulumi.Output<string>;
    /**
     * Identifier of the service the variable collection belongs to.
     */
    declare public readonly serviceId: pulumi.Output<string>;
    /**
     * Collection of variables.
     */
    declare public readonly variables: pulumi.Output<outputs.VariableCollectionVariable[]>;

    /**
     * Create a VariableCollection resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: VariableCollectionArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: VariableCollectionArgs | VariableCollectionState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as VariableCollectionState | undefined;
            resourceInputs["environmentId"] = state?.environmentId;
            resourceInputs["projectId"] = state?.projectId;
            resourceInputs["serviceId"] = state?.serviceId;
            resourceInputs["variables"] = state?.variables;
        } else {
            const args = argsOrState as VariableCollectionArgs | undefined;
            if (args?.environmentId === undefined && !opts.urn) {
                throw new Error("Missing required property 'environmentId'");
            }
            if (args?.serviceId === undefined && !opts.urn) {
                throw new Error("Missing required property 'serviceId'");
            }
            if (args?.variables === undefined && !opts.urn) {
                throw new Error("Missing required property 'variables'");
            }
            resourceInputs["environmentId"] = args?.environmentId;
            resourceInputs["serviceId"] = args?.serviceId;
            resourceInputs["variables"] = args?.variables;
            resourceInputs["projectId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(VariableCollection.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering VariableCollection resources.
 */
export interface VariableCollectionState {
    /**
     * Identifier of the environment the variable collection belongs to.
     */
    environmentId?: pulumi.Input<string | undefined>;
    /**
     * Identifier of the project the variable collection belongs to.
     */
    projectId?: pulumi.Input<string | undefined>;
    /**
     * Identifier of the service the variable collection belongs to.
     */
    serviceId?: pulumi.Input<string | undefined>;
    /**
     * Collection of variables.
     */
    variables?: pulumi.Input<pulumi.Input<inputs.VariableCollectionVariable>[] | undefined>;
}

/**
 * The set of arguments for constructing a VariableCollection resource.
 */
export interface VariableCollectionArgs {
    /**
     * Identifier of the environment the variable collection belongs to.
     */
    environmentId: pulumi.Input<string>;
    /**
     * Identifier of the service the variable collection belongs to.
     */
    serviceId: pulumi.Input<string>;
    /**
     * Collection of variables.
     */
    variables: pulumi.Input<pulumi.Input<inputs.VariableCollectionVariable>[]>;
}
